#!/bin/sh

create_repo() {
	git init
	git remote add -f origin $1
	git config core.sparseCheckout true
	echo "chrome-extension/" >> .git/info/sparse-checkout
	git pull origin master
}

if [ $# -ne 1 ] ; then
    echo "Illegal number of parameters"
    exit 1
fi

create_repo $1